In [1]:
import pandas as pd

comparison = pd.DataFrame({
    "Metric": ["AUC", "Gini", "KS"],
    "Champion": [0.5969, 0.1938, 0.1455],
    "Challenger": [0.5962, 0.1925, 0.1413]
})

comparison

  Metric  Champion  Challenger
0    AUC    0.5969      0.5962
1   Gini    0.1938      0.1925
2     KS    0.1455      0.1413

In [2]:
comparison["Champion_Better"] = (
    comparison["Champion"] > comparison["Challenger"]
)

comparison

  Metric  Champion  Challenger  Champion_Better
0    AUC    0.5969      0.5962             True
1   Gini    0.1938      0.1925             True
2     KS    0.1455      0.1413             True

In [3]:
comparison.to_csv(
    "../outputs/metrics/champion_vs_challenger.csv",
    index=False
)

print("Champion vs Challenger comparison saved.")

Champion vs Challenger comparison saved.